`timescale 1ns/1ps

// ============================================================================
// VitalSoC GPIO
//
// GPIO BASE ADDRESS: 0x3000_0000
//
// Register Map
// ----------------------------------------------------------------------------
// Offset       Address          Register       Access       Valid bits
// ----------------------------------------------------------------------------
// 0x00         0x3000_0000     GPIO_LED       RW           [15:0]
// 0x04         0x3000_0004     GPIO_SW        R            [15:0]
// 0x08         0x3000_0008     GPIO_BTN       R            [4:0]
// ----------------------------------------------------------------------------
//
// All registers are 32 bits wide.
// Unused bits read as 0.
//
// GPIO_SW and GPIO_BTN use two-flop synchronizers.
// Hardware debounce is NOT implemented.
//
// Writes to GPIO_SW and GPIO_BTN are ignored.
//
// Unmapped GPIO offsets complete normally and return 0xDEADBEEF.
//
// ============================================================================

module gpio (

    input             clk,
    input             resetn,

    // Peripheral select generated by SoC address decoder
    input             sel,

    // Byte write strobes
    input      [3:0]  wstrb,

    // Address inside GPIO peripheral
    // This is expected to be mem_addr[4:2].
    //
    // 3'd0 -> 0x00 -> GPIO_LED
    // 3'd1 -> 0x04 -> GPIO_SW
    // 3'd2 -> 0x08 -> GPIO_BTN
    input      [2:0]  addr,

    // CPU write data
    input      [31:0] wdata,

    // CPU read data
    output reg [31:0] rdata,

    // Peripheral acknowledge
    output reg        ready,

    // ------------------------------------------------------------------------
    // GPIO pins
    // ------------------------------------------------------------------------

    output     [15:0] led,
    input      [15:0] sw,
    input      [4:0]  btn
);


    // =========================================================================
    // GPIO_LED
    // =========================================================================

    reg [15:0] led_r;


    // =========================================================================
    // GPIO_SW synchronizer
    // =========================================================================

    reg [15:0] sw_s0;
    reg [15:0] sw_s1;


    // =========================================================================
    // GPIO_BTN synchronizer
    // =========================================================================

    reg [4:0] btn_s0;
    reg [4:0] btn_s1;


    // =========================================================================
    // LED OUTPUT
    // =========================================================================

    assign led = led_r;


    // =========================================================================
    // BUS CONTROL
    // =========================================================================

    // Accept one transfer when selected and not already acknowledged.
    wire xfer = sel && !ready;

    // A write request exists when any byte strobe is asserted.
    wire wr = |wstrb;


    // =========================================================================
    // GPIO SEQUENTIAL LOGIC
    // =========================================================================

    always @(posedge clk) begin

        // ---------------------------------------------------------------------
        // Two-flop synchronizer for switches
        // ---------------------------------------------------------------------

        sw_s0 <= sw;
        sw_s1 <= sw_s0;


        // ---------------------------------------------------------------------
        // Two-flop synchronizer for buttons
        // ---------------------------------------------------------------------

        btn_s0 <= btn;
        btn_s1 <= btn_s0;


        // ---------------------------------------------------------------------
        // RESET
        // ---------------------------------------------------------------------

        if (!resetn) begin

            ready <= 1'b0;

            led_r <= 16'h0000;

            sw_s0 <= 16'h0000;
            sw_s1 <= 16'h0000;

            btn_s0 <= 5'h00;
            btn_s1 <= 5'h00;

        end

        else begin

            // -----------------------------------------------------------------
            // One-cycle acknowledge
            // -----------------------------------------------------------------

            ready <= xfer;


            // -----------------------------------------------------------------
            // WRITE ACCESS
            // -----------------------------------------------------------------

            if (xfer && wr) begin

                case (addr)

                    // =========================================================
                    // GPIO_LED
                    //
                    // Offset: 0x00
                    // Access: RW
                    // Bits:   [15:0]
                    // =========================================================

                    3'd0: begin

                        // Byte 0 -> LED[7:0]
                        if (wstrb[0])
                            led_r[7:0] <= wdata[7:0];

                        // Byte 1 -> LED[15:8]
                        if (wstrb[1])
                            led_r[15:8] <= wdata[15:8];

                        // Bytes 2 and 3 correspond to reserved bits.
                        // They are ignored.

                    end


                    // =========================================================
                    // GPIO_SW
                    //
                    // Read-only.
                    // Writes are ignored.
                    // =========================================================

                    3'd1: begin
                        // Intentionally empty.
                    end


                    // =========================================================
                    // GPIO_BTN
                    //
                    // Read-only.
                    // Writes are ignored.
                    // =========================================================

                    3'd2: begin
                        // Intentionally empty.
                    end


                    // =========================================================
                    // RESERVED / UNMAPPED
                    //
                    // Writes are ignored.
                    // =========================================================

                    default: begin
                        // Intentionally empty.
                    end

                endcase

            end

        end

    end


    // =========================================================================
    // GPIO READ LOGIC
    // =========================================================================

    always @(posedge clk) begin

        case (addr)

            // -----------------------------------------------------------------
            // GPIO_LED
            //
            // Address: 0x3000_0000
            //
            // [31:16] = reserved = 0
            // [15:0]  = LED
            // -----------------------------------------------------------------

            3'd0: begin

                rdata <= {
                    16'h0000,
                    led_r
                };

            end


            // -----------------------------------------------------------------
            // GPIO_SW
            //
            // Address: 0x3000_0004
            //
            // [31:16] = reserved = 0
            // [15:0]  = synchronized switch state
            // -----------------------------------------------------------------

            3'd1: begin

                rdata <= {
                    16'h0000,
                    sw_s1
                };

            end


            // -----------------------------------------------------------------
            // GPIO_BTN
            //
            // Address: 0x3000_0008
            //
            // [31:5] = reserved = 0
            // [4:0]  = synchronized button state
            // -----------------------------------------------------------------

            3'd2: begin

                rdata <= {
                    27'h0000000,
                    btn_s1
                };

            end


            // -----------------------------------------------------------------
            // RESERVED / UNMAPPED
            //
            // Global specification:
            // unmapped address reads return 0xDEADBEEF.
            // -----------------------------------------------------------------

            default: begin

                rdata <= 32'hDEADBEEF;

            end

        endcase

    end

endmodule